let
  -- raise an exception by divided 0
  main = 1 / 0
in main
